backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pagine"
    files:
      - label: "Homepage"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Contenuto", name: "body", widget: "markdown" }


  - name: "download_utili"
    label: "Download Utili"
    folder: "contenuti/download_utili"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "File", name: "file", widget: "file" }
