
backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "contenuti"
    label: "Contenuti del sito"
    files:
      - file: "index.html"
        label: "Contenuti Principali"
        name: "index"
        fields:
          - { label: "Titolo", name: "titolo", widget: "string" }
          - { label: "Sottotitolo", name: "sottotitolo", widget: "string" }
          - { label: "Chi siamo", name: "chi_siamo", widget: "text" }
          - { label: "Attività", name: "attivita", widget: "text" }
          - { label: "Contatti", name: "contatti", widget: "text" }
